"""
agents.py — Specialist agents, each running a genuine ReAct loop.

FLAWS FIXED vs original:
  1. Original used prompt | llm chains — no tool use, no loops, no autonomy.
     Every agent here uses create_react_agent() from langgraph so they can
     Reason → Act (call a tool) → Observe the result → Reason again.

  2. Original had no retry / self-reflection.  Each agent here has a
     _reflect_and_validate() step: the agent's output is scored by the LLM
     itself; if the score is below a threshold the agent re-runs with the
     critique injected, up to MAX_RETRIES times.

  3. Original hard-coded the Mistral API key as a plaintext fallback string
     directly in source code — a serious security flaw.  That is removed.
     The key must come from the environment or the Streamlit sidebar only.

  4. Original defined Agent 6 (performance evaluator) but labelled it in the
     docstring as "Agent 6" while only defining agents 1-4 plus 6, skipping
     a "Agent 5" entirely.  The numbering is now consistent and a proper
     mock-interview facilitator agent (step 5) is added.
"""

import os
import json
import logging
from typing import Any, Optional

from pydantic import BaseModel, Field, model_validator
from typing import List

from langchain_mistralai import ChatMistralAI
from langchain_core.messages import HumanMessage, SystemMessage, AIMessage, ToolMessage
from dotenv import load_dotenv

from tools import (
    RESUME_TOOLS,
    JD_TOOLS,
    SKILL_GAP_TOOLS,
    QUESTION_TOOLS,
    EVALUATOR_TOOLS,
)

load_dotenv()
logger = logging.getLogger(__name__)

MAX_RETRIES = 2          # how many self-reflection retry cycles per agent
REFLECT_THRESHOLD = 6   # score out of 10 below which agent re-runs


# Helper to coerce dictionary fields generated by LLMs to standard strings
def _coerce_to_string(item: Any) -> str:
    if isinstance(item, str):
        return item
    if isinstance(item, dict):
        parts = []
        for key, val in item.items():
            if val is not None:
                if len(item) == 1:
                    parts.append(str(val))
                else:
                    parts.append(f"{key}: {val}")
        return ", ".join(parts) if parts else str(item)
    return str(item)


class ResumeAnalysis(BaseModel):
    candidate_name: str = Field(description="Full name of the candidate")
    email: Optional[str] = Field(description="Email address of the candidate")
    education: List[str] = Field(description="List of educational qualifications")
    experience_years: float = Field(description="Estimated total professional experience in years")
    skills: List[str] = Field(description="Key technical and soft skills identified")
    projects: List[str] = Field(description="Summary of key projects or achievements")
    strengths: List[str] = Field(description="Top 3-4 candidate strengths")
    weaknesses: List[str] = Field(description="Potential areas of weakness or gaps")

    @model_validator(mode="before")
    @classmethod
    def coerce_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            for field in ["education", "skills", "projects", "strengths", "weaknesses"]:
                if field in data and isinstance(data[field], list):
                    data[field] = [_coerce_to_string(x) for x in data[field]]
        return data


class JDAnalysis(BaseModel):
    job_title: str = Field(description="The job title from the job description")
    company_name: Optional[str] = Field(description="Name of the company")
    required_experience_years: float = Field(description="Required minimum years of experience")
    required_skills: List[str] = Field(description="Core must-have skills")
    preferred_skills: List[str] = Field(description="Nice-to-have skills")
    key_responsibilities: List[str] = Field(description="Primary responsibilities")

    @model_validator(mode="before")
    @classmethod
    def coerce_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            for field in ["required_skills", "preferred_skills", "key_responsibilities"]:
                if field in data and isinstance(data[field], list):
                    data[field] = [_coerce_to_string(x) for x in data[field]]
        return data


class SkillGapReport(BaseModel):
    match_score: int = Field(description="Overall skill match percentage 0-100")
    matching_skills: List[str] = Field(description="Skills matching the JD")
    missing_skills: List[str] = Field(description="Required skills missing from resume")
    nice_to_have_matches: List[str] = Field(description="Preferred skills the candidate has")
    bridging_strategy: List[str] = Field(description="Actionable steps to address gaps")
    market_context: List[str] = Field(
        default_factory=list,
        description="Real-world market demand notes gathered via web search"
    )

    @model_validator(mode="before")
    @classmethod
    def coerce_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            for field in ["matching_skills", "missing_skills", "nice_to_have_matches", "bridging_strategy", "market_context"]:
                if field in data and isinstance(data[field], list):
                    data[field] = [_coerce_to_string(x) for x in data[field]]
        return data


class InterviewQuestion(BaseModel):
    question_id: int
    question_text: str
    question_type: str = Field(description="Technical | Behavioral | Resume-specific")
    expected_key_points: List[str]
    model_answer: str
    source_reference: Optional[str] = Field(
        default=None,
        description="URL or source where a similar real question was found"
    )

    @model_validator(mode="before")
    @classmethod
    def coerce_fields(cls, data: Any) -> Any:
        if isinstance(data, dict):
            for field in ["expected_key_points"]:
                if field in data and isinstance(data[field], list):
                    data[field] = [_coerce_to_string(x) for x in data[field]]
        return data


class QuestionList(BaseModel):
    questions: List[InterviewQuestion] = Field(description="Exactly 5 tailored interview questions")


class AnswerEvaluation(BaseModel):
    question_id: int
    question_text: str
    user_answer: str
    score: int = Field(description="Score out of 10")
    strengths: List[str]
    weaknesses: List[str]
    suggested_improvement: str


class PerformanceEvaluation(BaseModel):
    overall_readiness_score: int = Field(description="Placement readiness 0-100")
    evaluations: List[AnswerEvaluation]
    key_strengths: List[str]
    key_development_areas: List[str]
    final_verdict: str
    reflection_cycles: int = Field(
        default=0,
        description="How many self-reflection retries this evaluation took"
    )

# ── Shared LLM factory ────────────────────────────────────────────────────────

def get_llm(api_key: Optional[str] = None) -> ChatMistralAI:
    """
    FLAW FIXED: original had a hardcoded plaintext API key as a fallback.
    Now we only accept the key from the environment or caller — never from
    source code.
    """
    key = api_key or os.getenv("MISTRAL_API_KEY")
    if not key:
        raise ValueError(
            "MISTRAL_API_KEY not found. Set it in your .env file or pass it "
            "via the Streamlit sidebar."
        )
    return ChatMistralAI(model="mistral-small-2506", temperature=0, api_key=key)


# ── Self-reflection helper ────────────────────────────────────────────────────

def _reflect(llm: ChatMistralAI, output_json: str, agent_name: str) -> tuple[bool, str]:
    """
    Ask the LLM to score its own output.  Returns (accept: bool, critique: str).
    This is the core of the retry loop — if the agent scores itself below
    REFLECT_THRESHOLD it re-runs with the critique injected.
    """
    prompt = (
        f"You are a strict quality reviewer for the {agent_name}.\n"
        f"Review the following JSON output and score it from 1-10 for completeness, "
        f"accuracy, and usefulness.\n\n"
        f"OUTPUT:\n{output_json}\n\n"
        f"Respond ONLY with a JSON object: "
        f'{{ "score": <int>, "critique": "<one paragraph of specific issues>" }}\n'
        f"No markdown, no preamble."
    )
    try:
        response = llm.invoke([HumanMessage(content=prompt)])
        data = json.loads(response.content.strip())
        score = int(data.get("score", 0))
        critique = data.get("critique", "")
        accept = score >= REFLECT_THRESHOLD
        logger.info(f"[{agent_name}] reflection score={score} accept={accept}")
        return accept, critique
    except Exception as e:
        logger.warning(f"[{agent_name}] reflection parsing failed: {e} — accepting output")
        return True, ""


# ── Agent runner helper ─────────────────────
def _sanitize_response_tool_calls(response: Any, seen_ids: set) -> Any:
    """
    Sanitizes the tool call IDs in a newly received AIMessage.
    Ensures each tool call ID is unique and doesn't conflict with any IDs
    already seen in this conversation.
    """
    import uuid
    if hasattr(response, "tool_calls") and response.tool_calls:
        raw_tool_calls = response.additional_kwargs.get("tool_calls", [])
        
        for idx, tc in enumerate(response.tool_calls):
            orig_id = tc.get("id")
            
            # If the ID is duplicate or empty, generate a new unique one
            if not orig_id or orig_id in seen_ids:
                new_id = f"call_{uuid.uuid4().hex[:8]}"
                tc["id"] = new_id
                
                # Sync with the raw tool calls in additional_kwargs
                if idx < len(raw_tool_calls):
                    tc_raw = raw_tool_calls[idx]
                    if isinstance(tc_raw, dict):
                        tc_raw["id"] = new_id
                    elif hasattr(tc_raw, "id"):
                        try:
                            setattr(tc_raw, "id", new_id)
                        except Exception:
                            pass
                seen_ids.add(new_id)
            else:
                seen_ids.add(orig_id)
                
    return response


def _run_react_agent(
    llm: ChatMistralAI,
    tools: list,
    system_prompt: str,
    user_message: str,
    agent_name: str,
) -> str:
    """
    Runs a custom ReAct loop that executes tools and feeds results back to the LLM.
    Guards against "Duplicate tool call id in assistant message" errors by sanitizing
    new tool call IDs immediately after LLM invocation.
    """
    from langchain_core.messages import ToolMessage
    
    llm_with_tools = llm.bind_tools(tools) if tools else llm
    
    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=user_message),
    ]
    
    tool_map = {t.name: t for t in tools}
    seen_ids = set()
    max_steps = 10
    
    for step in range(max_steps):
        logger.info(f"[{agent_name}] Step {step+1}: invoking LLM...")
        
        # Invoke LLM
        response = llm_with_tools.invoke(messages)
        
        # Sanitize tool calls in this response to prevent duplicate tool call IDs
        response = _sanitize_response_tool_calls(response, seen_ids)
                
        # Add response to history
        print("\n===== MESSAGE HISTORY =====")

        for i, msg in enumerate(messages):
            print(f"\nMessage {i}")
            print(type(msg))

            if hasattr(msg, "tool_calls"):
                print("tool_calls =", msg.tool_calls)
        messages.append(response)
        
        # Check if LLM requested tools
        if not hasattr(response, "tool_calls") or not response.tool_calls:
            logger.info(f"[{agent_name}] LLM completed on step {step+1}")
            return response.content
            
        logger.info(f"[{agent_name}] LLM requested tools: {[tc['name'] for tc in response.tool_calls]}")
        
        # Execute tools
        print("\n===== TOOL EXECUTION =====")
        print("Tool Calls Count:", len(response.tool_calls))
        for tc in response.tool_calls:
            t_name = tc["name"]
            t_args = tc["args"]
            t_id = tc["id"]
            print("Executing:", t_name)
            print("Tool ID:", t_id)
            if t_name in tool_map:
                try:
                    logger.info(f"[{agent_name}] Executing tool '{t_name}' with args {t_args}")
                    tool_result = tool_map[t_name].invoke(t_args)
                except Exception as e:
                    tool_result = f"Error executing tool '{t_name}': {e}"
            else:
                tool_result = f"Error: Tool '{t_name}' is not available."
                
            messages.append(ToolMessage(content=str(tool_result), tool_call_id=t_id))
            
    logger.warning(f"[{agent_name}] Reached max ReAct steps ({max_steps}) without completion.")
    return messages[-1].content



# ── Agent 1: Resume Analyzer ──────────────────────────────────────────────────

def run_resume_analyzer(resume_text: str, api_key: Optional[str] = None) -> ResumeAnalysis:
    """
    Analyzes the candidate's resume.  Can call web_search / verify_skill_definition
    to look up unfamiliar technologies before reporting them.
    Retries up to MAX_RETRIES times if self-reflection score is too low.
    """
    llm = get_llm(api_key)
    system = (
        "You are an expert Resume Analyzer Agent.\n"
        "Extract ALL relevant details from the resume.\n"
        "If you encounter a skill or technology you are not certain about, "
        "use the verify_skill_definition tool before including it.\n"
        "If the resume mentions a company or project that needs context, "
        "use web_search to gather it.\n"
        "Return your final answer as a JSON object matching the ResumeAnalysis schema:\n"
        "candidate_name, email, education (list), experience_years (float), "
        "skills (list), projects (list), strengths (list), weaknesses (list).\n"
        "Output ONLY valid JSON. No markdown fences, no preamble."
    )
    user_msg = f"Analyze this resume:\n\n{resume_text}"

    for attempt in range(MAX_RETRIES + 1):
        raw = _run_react_agent(llm, RESUME_TOOLS, system, user_msg, "ResumeAnalyzer")
        accept, critique = _reflect(llm, raw, "ResumeAnalyzer")
        if accept:
            break
        logger.info(f"[ResumeAnalyzer] retry {attempt+1}: {critique}")
        user_msg = (
            f"Previous attempt was rejected with this critique:\n{critique}\n\n"
            f"Please redo the analysis, fixing the identified issues.\n\n"
            f"Original resume:\n{resume_text}"
        )

    # Parse JSON → Pydantic
    try:
        clean = raw.strip().lstrip("```json").lstrip("```").rstrip("```").strip()
        return ResumeAnalysis.model_validate_json(clean)
    except Exception as e:
        logger.error(f"[ResumeAnalyzer] JSON parse failed: {e}\nRaw: {raw[:300]}")
        raise ValueError(f"ResumeAnalyzer produced invalid JSON: {e}")


# ── Agent 2: JD Analyzer ──────────────────────────────────────────────────────

def run_jd_analyzer(jd_text: str, api_key: Optional[str] = None) -> JDAnalysis:
    """
    Parses the job description.  Uses research_company to fetch real company
    background so the analysis is richer than just reading the JD text.
    """
    llm = get_llm(api_key)
    system = (
        "You are an expert Job Description Analyzer Agent.\n"
        "Extract all key requirements, experience levels, and responsibilities.\n"
        "If a company name is visible, use research_company to gather background "
        "on the company's tech stack and culture — this enriches the analysis.\n"
        "If any required skill seems niche or ambiguous, use web_search to clarify it.\n"
        "Return your final answer as a JSON object matching JDAnalysis schema:\n"
        "job_title, company_name, required_experience_years (float), "
        "required_skills (list), preferred_skills (list), key_responsibilities (list).\n"
        "Output ONLY valid JSON. No markdown fences, no preamble."
    )
    user_msg = f"Analyze this job description:\n\n{jd_text}"

    for attempt in range(MAX_RETRIES + 1):
        raw = _run_react_agent(llm, JD_TOOLS, system, user_msg, "JDAnalyzer")
        accept, critique = _reflect(llm, raw, "JDAnalyzer")
        if accept:
            break
        user_msg = (
            f"Critique from previous attempt:\n{critique}\n\n"
            f"Redo the analysis fixing those issues.\n\nOriginal JD:\n{jd_text}"
        )

    try:
        clean = raw.strip().lstrip("```json").lstrip("```").rstrip("```").strip()
        return JDAnalysis.model_validate_json(clean)
    except Exception as e:
        raise ValueError(f"JDAnalyzer produced invalid JSON: {e}")


# ── Agent 3: Skill Gap Analyzer ───────────────────────────────────────────────

def run_skill_gap_analyzer(
    resume_analysis: ResumeAnalysis,
    jd_analysis: JDAnalysis,
    api_key: Optional[str] = None,
) -> SkillGapReport:
    """
    Compares resume against JD.  Uses check_skill_demand to verify whether
    'missing' skills are actually critical in the real job market — avoids
    penalising candidates for obscure nice-to-haves.
    """
    llm = get_llm(api_key)
    system = (
        "You are an expert Skill Gap Analyzer Agent.\n"
        "Compare the candidate's skills against the job requirements.\n"
        "For each skill labelled as 'missing', call check_skill_demand to verify "
        "how critical it actually is in the current job market before reporting it.\n"
        "Compute a match_score (0-100) that reflects both hard skills and experience.\n"
        "Provide a market_context list with 2-3 real-world notes gathered from your searches.\n"
        "Return JSON matching SkillGapReport schema:\n"
        "match_score (int), matching_skills (list), missing_skills (list), "
        "nice_to_have_matches (list), bridging_strategy (list), market_context (list).\n"
        "Output ONLY valid JSON. No markdown fences, no preamble."
    )
    user_msg = (
        f"Resume Analysis:\n{resume_analysis.model_dump_json(indent=2)}\n\n"
        f"JD Analysis:\n{jd_analysis.model_dump_json(indent=2)}"
    )

    for attempt in range(MAX_RETRIES + 1):
        raw = _run_react_agent(llm, SKILL_GAP_TOOLS, system, user_msg, "SkillGapAnalyzer")
        accept, critique = _reflect(llm, raw, "SkillGapAnalyzer")
        if accept:
            break
        user_msg += f"\n\nCritique:\n{critique}\nPlease fix these issues and redo."

    try:
        clean = raw.strip().lstrip("```json").lstrip("```").rstrip("```").strip()
        return SkillGapReport.model_validate_json(clean)
    except Exception as e:
        raise ValueError(f"SkillGapAnalyzer produced invalid JSON: {e}")


# ── Agent 4: Question Generator ───────────────────────────────────────────────

def run_question_generator(
    resume_analysis: ResumeAnalysis,
    jd_analysis: JDAnalysis,
    skill_gap_report: SkillGapReport,
    api_key: Optional[str] = None,
) -> QuestionList:
    """
    Generates exactly 5 interview questions.  Uses research_interview_questions
    to find real questions asked for this role — so output is grounded in
    actual interview patterns, not just LLM imagination.
    """
    llm = get_llm(api_key)
    system = (
        "You are an expert Interview Question Generator Agent.\n"
        "Generate exactly 5 tailored questions:\n"
        "  • 3 technical questions targeting skill gaps or core JD requirements\n"
        "  • 1 behavioral / situational questions based on key responsibilities\n"
        "  • 1 resume-specific question about the candidate's projects\n"
        "For each question use research_interview_questions to find real examples "
        "of similar questions asked in actual interviews, and include the source URL.\n"
        "Provide expected_key_points and a model_answer for each question.\n"
        "Return JSON matching QuestionList schema with a 'questions' array of 5 items.\n"
        "Each item: question_id, question_text, question_type, expected_key_points (list), "
        "model_answer, source_reference (URL or null).\n"
        "Output ONLY valid JSON. No markdown fences, no preamble."
    )
    user_msg = (
        f"Resume:\n{resume_analysis.model_dump_json(indent=2)}\n\n"
        f"JD:\n{jd_analysis.model_dump_json(indent=2)}\n\n"
        f"Skill gaps:\n{skill_gap_report.model_dump_json(indent=2)}"
    )

    for attempt in range(MAX_RETRIES + 1):
        raw = _run_react_agent(llm, QUESTION_TOOLS, system, user_msg, "QuestionGenerator")
        accept, critique = _reflect(llm, raw, "QuestionGenerator")
        if accept:
            break
        user_msg += f"\n\nCritique:\n{critique}\nPlease fix and regenerate all 5 questions."

    try:
        clean = raw.strip().lstrip("```json").lstrip("```").rstrip("```").strip()
        return QuestionList.model_validate_json(clean)
    except Exception as e:
        raise ValueError(f"QuestionGenerator produced invalid JSON: {e}")


# ── Agent 5: Performance Evaluator ────────────────────────────────────────────

def run_performance_evaluator(
    questions: List[InterviewQuestion],
    user_answers: dict,
    api_key: Optional[str] = None,
) -> PerformanceEvaluation:
    """
    Evaluates candidate answers with self-reflection.
    FLAW FIXED (original): original evaluator ran once with no feedback loop.
    Here the evaluator scores itself: if its own quality score is below
    REFLECT_THRESHOLD it re-evaluates, making the feedback more constructive
    and less likely to miss important points.
    """
    llm = get_llm(api_key)

    qa_blocks = []
    for q in questions:
        ans = user_answers.get(str(q.question_id)) or "No answer provided."
        qa_blocks.append(
            f"Q{q.question_id} [{q.question_type}]: {q.question_text}\n"
            f"Expected key points: {', '.join(q.expected_key_points)}\n"
            f"Model answer: {q.model_answer}\n"
            f"Candidate answer: {ans}"
        )
    qa_text = "\n\n---\n\n".join(qa_blocks)

    system = (
        "You are an expert Performance Evaluator Agent.\n"
        "Evaluate each candidate answer against the question, expected key points, "
        "and model answer.  Score each out of 10.  Be honest but constructive.\n"
        "Compute overall_readiness_score (0-100) as a weighted average.\n"
        "Return JSON matching PerformanceEvaluation schema:\n"
        "overall_readiness_score (int), evaluations (list of AnswerEvaluation), "
        "key_strengths (list), key_development_areas (list), final_verdict (str), "
        "reflection_cycles (int, starts at 0).\n"
        "Each AnswerEvaluation: question_id, question_text, user_answer, score (int), "
        "strengths (list), weaknesses (list), suggested_improvement (str).\n"
        "Output ONLY valid JSON. No markdown fences, no preamble."
    )
    user_msg = f"Evaluate the following interview Q&A:\n\n{qa_text}"

    reflection_cycles = 0
    for attempt in range(MAX_RETRIES + 1):
        raw = _run_react_agent(llm, EVALUATOR_TOOLS, system, user_msg, "PerformanceEvaluator")
        accept, critique = _reflect(llm, raw, "PerformanceEvaluator")
        if accept:
            break
        reflection_cycles += 1
        user_msg = (
            f"Your previous evaluation was found lacking:\n{critique}\n\n"
            f"Please re-evaluate more carefully.\n\nOriginal Q&A:\n{qa_text}"
        )

    try:
        import json
        import re

        clean = raw.strip().lstrip("```json").lstrip("```").rstrip("```").strip()
        data = json.loads(clean)
        for item in data.get("evaluations", []):
            qid = item.get("question_id")
               
            if isinstance(qid, str):
                match = re.search(r"\d+", qid)

                if match:
                    item["question_id"] = int(match.group())

        clean = json.dumps(data)

        result = PerformanceEvaluation.model_validate_json(clean)
        result.reflection_cycles = reflection_cycles

        return result

    except Exception as e:
        raise ValueError(f"PerformanceEvaluator produced invalid JSON: {e}")
